version: "3.9"
services:
#-----------API服務----------------- #
    api:
        image: api
        build: ./api
        ports:
        - 2769:5000
        environment:
        - ENVIRONMENT=production   
        depends_on:
            - mongo 
#-----------資料庫服務 (MongoDB)----------------- #
    mongo:
        image: mongo
        restart: always
        ports:
                - 1769:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
                - mongodb-data:/data/db                           
volumes:
  mongodb-data: