version: "3.9"
services:
#-----------API服務----------------- #
    api:
        image: api
        build: ./api
        ports:
        - 2769:5000
        environment:
        - ENVIRONMENT=production   
        depends_on:
            - mongo 
#-----------資料庫服務 (MongoDB)----------------- #
    mongo:
        image: mongo
        restart: always
        ports:
                - 1769:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
                - mongodb-data:/data/db
    #------------MongoDB網頁版管理系統--------------------- #
    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 5469:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
                - mongo                           
volumes:
  mongodb-data: